name: Build Go Project

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-nightly'
      - 'v*.*.*-alpha'
      - 'v*.*.*-beta'
      - 'v*.*.*-rc'
      - 'v*.*.*-stable'
      - 'v*.*.*-final'

jobs:
  build:
    name: Build Server and Hunter CLI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.4

      - name: Build Server
        run: |
          cd cmd/server
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o orion
          echo "Starting server for a short test..."
          timeout 5 ./orion --port=6379 || echo "Server stopped after short test."

      - name: Build Hunter CLI
        run: |
          cd cmd/hunter
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o hunter
          echo "Verifying Hunter CLI build..."
          ./hunter connect 127.0.0.1:6379 || echo "Hunter CLI build successful, but unable to connect to server as expected."

      - name: Upload Server Binary
        uses: actions/upload-artifact@v3
        with:
          name: server-${{ matrix.goos }}-${{ matrix.goarch }}
          path: cmd/server/orion

      - name: Upload Hunter CLI Binary
        uses: actions/upload-artifact@v3
        with:
          name: hunter-${{ matrix.goos }}-${{ matrix.goarch }}
          path: cmd/hunter/hunter
