# This workflow will build a golang project and release binaries on GitHub
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - 'v*' # Runs on version tags (e.g., v1.0, v1.1.0, etc.)
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build Orion for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o orion.exe ./cmd/server/orion.go
      shell: bash

    - name: Build Hunter for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o hunter.exe ./cmd/hunter/hunter.go
      shell: bash

    - name: Test
      run: go test -v ./...

    - name: Upload Binaries to GitHub Release
      id: upload-release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          orion.exe
          hunter.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
