name: Build Go Project

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-nightly'
      - 'v*.*.*-alpha'
      - 'v*.*.*-beta'
      - 'v*.*.*-rc'
      - 'v*.*.*-stable'
      - 'v*.*.*-final'

jobs:
  build:
    name: Build Server and Hunter CLI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.4

      - name: Build and Release Binaries
        uses: wangyoucao577/go-release-action@v1.50
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: ./cmd/server ./cmd/hunter
          binary_name: server hunter
          extra_files: LICENSE README.md
